name: staff_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  audioplayers: ^4.1.0
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  responsive_sizer: ^3.1.1
  get: ^4.6.5
  group_radio_button: ^1.3.0
  qr_code_scanner: ^1.0.1
  flutter_rating_bar: ^4.0.1
  dashed_rect: ^0.0.4
  date_picker_timeline: ^1.2.3
  table_calendar: ^3.0.8
  flutter_staggered_grid_view: ^0.6.2
  just_the_tooltip: ^0.0.12
  text_to_speech: ^0.2.3
  flutter_calendar_carousel: ^2.4.1
  shared_preferences: ^2.1.0
  dropdown_button2: ^1.0.0
  autoscale_tabbarview: ^1.0.2
  pin_code_fields: ^7.4.0
  local_auth: ^2.1.6
  circular_countdown_timer: ^0.2.3
  syncfusion_flutter_datepicker: ^21.1.39
  fluttertoast: ^8.2.1
  image_picker: ^1.0.0
  dio: ^4.0.0
  qr_flutter: ^4.0.0
  flutter_local_notifications: ^14.1.1
  url_launcher: ^6.1.11
  open_file: ^3.3.1
  photo_view: ^0.14.0
  chewie: ^1.5.0
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.0.15
  flutter_cache_manager: ^3.3.0
  pdf_render: ^1.4.0
  file_picker: ^5.0.2
  permission_handler: ^10.4.3
  country_picker: ^2.0.20
  cached_network_image: ^3.2.3
# Google APIs
  geocoding: ^2.1.0
  google_maps_flutter: ^2.4.0
  google_places_flutter: ^2.0.6
  geolocator: ^9.0.2
#  flutter_pdfview: ^1.3.0
#  path_provider: ^2.0.15
  flutter_video_info: ^1.3.1
  equatable: ^2.0.5
  device_info_plus: ^9.0.2
  input_with_keyboard_control: ^1.0.8
  flutter_stripe: ^9.3.0
  pay: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  change_app_package_name: ^1.1.0
flutter_icons:
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  android: true
  ios: true
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/delete/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
